dotenv: .env
dependencies:
  - smartcontractkit/chainlink@1.1.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.1.0"
wallets:
  private_key: ${PRIVATE_KEY}
networks:
  default: development

  mainnet-fork-dev:
    pricefeed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
  rinkeby:
    pricefeed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"